-- AlterTable
ALTER TABLE "books" ADD COLUMN     "avgRating" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "ratingsCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ratingsSum" DOUBLE PRECISION NOT NULL DEFAULT 0;
